name: publish dev

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - gh-publish-webhook

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: "https://dev.lumina.eiger.co/hooks/deploy-dev.sh"
          webhook_secret: "foo"